standard_id: oracle_19c
policies:
  expected_open_mode: READ WRITE
  expected_archivelog_mode: ARCHIVELOG
  min_tablespace_free_pct: 10
  min_tablespace_free_pct_warning: 20
  min_tablespace_free_pct_fail: 10
  min_tablespace_free_pct_critical: 5
  max_tablespace_used_pct_warning: 80
  max_tablespace_used_pct_fail: 90
  datafiles_autoextend_disabled_status: WARNING
  datafile_maxsize_used_pct_warning: 85
  datafile_maxsize_used_pct_fail: 95
  temp_usage_pct_warning: 80
  temp_usage_pct_fail: 95
  fra_not_configured_status: SKIPPED
  max_fra_used_pct_warning: 80
  max_fra_used_pct_critical: 95
  compatible_report_status: INFO
  expected_optimizer_features_enable: "19.1.0"
  expected_db_block_size: 8192
  min_open_cursors: 300
  min_processes: 300
  min_sessions: 450
  expected_audit_trail: DB
  expected_remote_login_passwordfile: EXCLUSIVE
  expected_recyclebin: ON
  expected_filesystemio_options: SETALL
  min_control_files: 2
  min_redo_log_groups: 3
  min_redo_log_members_per_group: 2
  expected_force_logging: "YES"
  expected_plsql_optimize_level: 2
